export const CATEGORIES_TYPES = {
  CNTRL_GET_CATEGORIES: 'CNTRL_GET_CATEGORIES',
  CNTRL_GET_CATEGORY: 'CNTRL_GET_CATEGORY'
}

export const ORDERS_TYPES = {
  CNTRL_POST_ORDER: 'CNTRL_POST_ORDER',
  RX_POST_ORDER: 'RX_POST_ORDER',
  RX_POST_ORDER_PENDIND: 'RX_POST_ORDER_PENDING',
  RX_POST_ORDER_REJECTED: 'RX_POST_ORDER_REJECTED',
  RX_POST_ORDER_DONE: 'RX_POST_ORDER_DONE'

}

export const PRODUCTS_TYPES = {
  CNTRL_GET_PRODUCTS: 'CNTRL_GET_PRODUCTS',
  RX_GET_PRODUCTS:'RX_GET_PRODUCTS',
  RX_GET_PRODUCTS_PENDING: 'RX_GET_PRODUCTS_PENDING',
  RX_GET_PRODUCTS_REJECTED: 'RX_GET_PRODUCTS_REJECTED',
  RX_GET_PRODUCTS_DONE: 'RX_GET_PRODUCTS_DONE',

  CNTRL_GET_PRODUCT: 'CNTRL_GET_PRODUCT',
  RX_ADD_TO_CART: 'RX_ADD_TO_CART',
  RX_REMOVE_FROM_CART: 'RX_REMOVE_FROM_CART',
  RX_REMOVE_All_FROM_CART: 'RX_REMOVE_All_FROM_CART',
  RX_CHANGE_QUANTITY: 'RX_CHANGE_QUANTITY'
}

export const USERS_TYPES = {
  CNTRL_LOGIN: 'CNTRL_LOGIN',
  RX_LOGIN: "RX_LOGIN",
  RX_LOGIN_PENDING: 'RX_LOGIN_PENDING',
  RX_LOGIN_DONE: 'RX_LOGIN_DONE',
  RX_LOGIN_REJECTED: 'RX_LOGIN_REJECTED',
  RX_SET_TOKEN: 'RX_SET_TOKEN',
  RX_REMOVE_TOKEN: 'RX_REMOVE_TOKEN',

  CNTRL_LOGOUT: 'CNTRL_LOGOUT',


  CNTRL_REGISTER: 'CNTRL_REGISTER',
  RX_REGISTER: "RX_REGISTER",
  RX_REGISTER_PENDING: 'RX_REGISTER_PENDING',
  RX_REGISTER_DONE: 'RX_REGISTER_DONE',

  CNTRL_GET_USERS: 'CNTRL_GET_USERS',
  CNTRL_GET_USER: 'CNTRL_GET_USER',
  CNTRL_DELETE_USER: 'CNTRL_DELETE_USER',
  CNTRL_SET_TOKEN: 'CNTRL_SET_TOKEN',
  CNTRL_REMOVE_TOKEN: 'CNTRL_REMOVE_TOKEN',
  CNTRL_SET_REGISTER_DATA:'CNTRL_SET_REGISTER_DATA'
}